name: CI

on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrage pip
          pip install -r requirements.txt

      - name: Print Hello
        run: echo Hi from &{{matrix.os}}
