name: CI

# Запускається при пуші у
# будь яку гілку, окрім main
on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      # Копіювання репозиторію
      - name: Checkout repository
        uses: actions/checkout@v3

      # Налаштування Пітону 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      # Встановлення потрібних бібліотек
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Налаштування віртуального монітору для запуску тестів на Ubuntu
      - name: Set up Xvfb and display variable (Ubuntu)
        # if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install xvfb
          sudo Xvfb :99 -ac &
          export DISPLAY=:99

      # Налаштування віртуального монітору для запуску тестів на Windows
      - name: Set up Xvfb and display variable (Windows)
        # if: matrix.os == 'windows-latest'
        run: echo "Skipping Xvfb setup for Windows"

      # Запуск тестів
      - name: Run tests with pytest
        run: pytest
