name: Nightly Tests

on:
  schedule:
    - cron: "55 16 * * *"

jobs:
  nightly-tests:
    runs-on: ubuntu-latest

    steps:
      # Копіювання репозиторію
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Налаштуваня Пітону 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      
      # Встановлення потрібних бібліотек
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Перевірка синтаксису
      - name: Run flake8
        run: flake8
      
      # Запуск тестів
      - name: Run tests with pytest
        run: pytest

      # Запуск аплікації
      - name: Run Application
        run: python main.py
