name: Create Release
on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Тут можуть бути ваші тести

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_NAME="Release Name"
          RELEASE_TAG="v1.0.0"
          RELEASE_BODY="Туть опис"
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"
          
          RESPONSE=$(curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "tag_name": "'"$RELEASE_TAG"'",
              "target_commitish": "main",
              "name": "'"$RELEASE_NAME"'",
              "body": "'"$RELEASE_BODY"'",
              "draft": false,
              "prerelease": false
            }' \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/releases")
          
          RELEASE_ID=$(echo "$RESPONSE" | jq -r '.id')
          echo "Created release with ID: $RELEASE_ID"
          
          
      - name: Publish Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_ID="${{ steps.create_release.outputs.release_id }}"
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"
          
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/releases/$RELEASE_ID/publish"

